version: '3.8'

services:
  # 1. Un servidor para páginas web (Nginx)
  web_server:
    image: nginx:latest
    container_name: servidor_web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - mi_red_app
    restart: always

  # 2. El cerebro de la app (Node.js)
  api_node:
    build: ./api-node
    container_name: backend_api
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db_postgres
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      - db_postgres
    networks:
      - mi_red_app

  # 3. Donde guardaremos la info (PostgreSQL)
  db_postgres:
    image: postgres:15
    container_name: base_datos_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mi_red_app
    restart: always

  # 4. Para ver la base de datos visualmente (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: administrador_pg
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db_postgres
    networks:
      - mi_red_app
    restart: always

  # 5. Para jugar con datos y código (Jupyter Lab)
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=root
    networks:
      - mi_red_app
    restart: always

networks:
  mi_red_app:
    driver: bridge

volumes:
  pg_data:
